export const muiPaletteLight = {
  primary: {
    main: "#C83B58",
    light: "#D36279",
    dark: "#8C293D",
    contrastText: "#ffffff",
    onHover: "#D36279",
    // container: ,
    // onContainer: ,
  },
  secondary: {
    main: "#DDFFF7",
    light: "#E3FFF8",
    dark: "#9AB2AC",
    contrastText: "rgba(0, 0, 0, 0.87)",
    // container: ,
    // onContainer: ,
  },
  warning: {
    main: "#FFD23F",
    light: "#FFDB65",
    dark: "#B2932C",
    contrastText: "rgba(0, 0, 0, 0.87)",
    // container: ,
    // onContainer: ,
  },
  error: {
    main: "#f44336",
    light: "#A83337",
    dark: "#660004",
    contrastText: "#ffffff",
    // container: ,
    // onContainer: ,
  },
  info: {
    main: "#2196f3",
    light: "#64b5f6",
    dark: "#1976d2",
    contrastText: "#ffffff",
    // container:,
    // onContainer: ,
  },
  success: {
    main: "#60A561",
    light: "#7FB780",
    dark: "#437343",
    contrastText: "rgba(0, 0, 0, 0.87)",
    // container: ,
    // onContainer: ,
  },
  scrappyBlack: {
    main: "#1A1423",
    light: "#47434F",
    dark: "#120E18",
    contrastText: "#ffffff",
    onHover: "#47434F",
    // container: ,
    // onContainer: ,
  },
};
